require "f-matchers"
require "active_record"

FileUtils.mkdir_p File.dirname(__FILE__) + '/../db/'
ActiveRecord::Base.establish_connection :adapter => "sqlite3", :database  => "db/test.sqlite3"
ActiveRecord::Base.connection.create_table(:documents,:force => true) do |t|
  t.timestamps
end
Dir[File.dirname(__FILE__) + "/support/**/*.rb"].each {|f| require f}

# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper.rb"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  config.before(:each) do
    Document.delete_all
  end

  config.after(:suite) do
    ActiveRecord::Base.connection.drop_table(:documents)
  end

end
